### ISSUE TITLE
Use authenticated GitHub API calls

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-deploy#62]
The staging job is often failing with this error:
```
Pushing kernel test branch for mainline
path: checkout/linux
repo: kernelci/linux
Traceback (most recent call last):
  File "/home/kernelci/kernelci-deploy/./kernel.py", line 87, in <module>
    ret = main(args)
  File "/home/kernelci/kernelci-deploy/./kernel.py", line 43, in main
    repo = kernelci.GITHUB.get_repo(repo_name)
  File "/usr/lib/python3/dist-packages/github/MainClass.py", line 294, in get_repo
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/lib/python3/dist-packages/github/Requester.py", line 275, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/lib/python3/dist-packages/github/Requester.py", line 286, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {'message': "API rate limit exceeded for 52.250.7.52. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", 'documentation_url': 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'}
```
So the solution would seem to be about using authenticated requests.

**Comment by mgalka** [comment]
Using authentication tokens in the requests via PyGithub looks easy, however it appears to me that kernelci doesn't [allow access with personal access tokens or the "fine-grained" ones](https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/setting-a-personal-access-token-policy-for-your-organization).

It looks it may need some actions from the organization owner. @gctucker: Can you help with this?

**Comment by nuclearcat** [comment]
To summarize, right now we are using "anonymous" requests which are severely throttled, but we need to implement authenticated Github API calls.
We need to generate Application(under KernelCI organization), which will have it's own key (.pem file), and this key will be used on each run to generate temporary token for authenticated API calls. This will allow to use much higher quota for API calls.
We need to make sure .pem file stored securely, do not add it to plaintext git.

* [ ] Generate application and pem key for it, document procedure
* [ ] Generate unique token using this pem key and verify github calls are authenticated
* [ ] Create PR, where you are integrate token generation and use to deploy scripts, but make sure if pem file is invalid or doesnt exist it will fallback to using old, unauthenticated calls, like before
* [ ] PR merged

**Comment by gctucker** [comment]
We could add the certificate to kernelci-project/secrets as an encrypted file.

**Comment by JenySadadia** [comment]
I have created a test app https://github.com/apps/test-github-app-kernelci and verified the above procedure.

**Comment by JenySadadia** [comment]
`X-Rate-Limit-Limit` for authenticated calls is `5000` requests per hour whereas for unauthenticated calls is `60` requests per hour.
This can be verified by using `github.enable_console_debug_logging()`, a method provided by `PyGithub`.

**Comment by JenySadadia** [comment]
@mgalka  Could you please help to create a github app for `KernelCI` organization as I am not authorized for it?
